"""Relate Users to books added foreign key

Revision ID: 3ed92e3a5e52
Revises: 454ec32fa7c2
Create Date: 2026-02-21 20:54:29.629430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel 


# revision identifiers, used by Alembic.
revision: str = '3ed92e3a5e52'
down_revision: Union[str, Sequence[str], None] = '454ec32fa7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Books', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Books', type_='foreignkey')
    op.drop_column('Books', 'user_uid')
    # ### end Alembic commands ###
