"""add roles to User

Revision ID: 454ec32fa7c2
Revises: af8ed88f3269
Create Date: 2026-02-21 17:18:51.696534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel 


# revision identifiers, used by Alembic.
revision: str = '454ec32fa7c2'
down_revision: Union[str, Sequence[str], None] = 'af8ed88f3269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
